language: haskell

# multi-ghc-travis code was adapted from ekmett/lens repository

env:
- GHCVER=7.4.2
- GHCVER=7.6.3
- GHCVER=7.8.3

matrix:
 allow_failures:
 # see https://github.com/neothemachine/monadiccp/issues/9
 - env: GHCVER=7.8.3

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
      export CABAL=cabal-1.18
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
    fi
  - $CABAL update
  - ghc-pkg list
  
install:
  - $CABAL install --dependencies-only --enable-tests
  
script:
  - $CABAL configure --enable-tests --enable-library-coverage && $CABAL build && $CABAL test
  
